#ifndef NUMERIC_CREATEQUADRATURECHEBFUNS_H
#define NUMERIC_CREATEQUADRATURECHEBFUNS_H

#include "Numeric/DllExport.h"
#include "API/Algorithm.h"

namespace Numeric
{

/**
 * Create orthogonal functions generated by a quadrature scheme.
 */
class NUMERIC_EXPORT CreateQuadratureChebfuns: public API::Algorithm
{
public:
  CreateQuadratureChebfuns();
  virtual std::string name() const {return "CreateQuadratureChebfuns";}
protected:
  virtual void exec();
};

} // NUMERIC

#endif // NUMERIC_CREATEQUADRATURECHEBFUNS_H
